### PR TITLE
Add prepend function and tests

### PR DESCRIPTION
**Pull request by tanhakabir**
Hey @cyjake 👋

I'm from the VS Code team and I was working on this issue: https://github.com/microsoft/vscode-remote-release/issues/4592 when I realized I needed a prepend function from your library and rather than hacking prepend myself in the extension I wanted to contribute. I followed what you did in the `append` function and added a `prepend` function along with the same set of tests you had for `append`.

One part I wasn't completely certain about but I assumed the behavior of is when you have a config that is something like this:
```
Host test

Host test2
    Hostname google.com
```

and you prepend:
```javascript
config.prepend({
      HostName: 'example.com',
      User: 'brian'
    })
```

I assumed the result should add the fields to the first config from the old config.
```
Host test
    Hostname example.com
    User brian

Host test2
    Hostname google.com
```

### CODE REVIEW

**Comment by tanhakabir** [comment]
Added flag to enable prepending below Include directives as well. To support the scenarios described in https://github.com/microsoft/vscode-remote-release/issues/4592#issuecomment-947168919

**Comment by cyjake** [comment]
@tanhakabir Thanks for the pr! About the question in the pr description, in my first thought the expected result should be:

```
HostName example.com
User brian

Host test

Host test2
    HostName google.com
```

This result doesn't make any sense because it shadows `Host test2` section, but I think we should keep `prepend()` simple. For example, if we prepend:

```js
config.prepend({
  IdentityFile: '~/.ssh/id_rsa',
})
```

I'd expect the result to be:

```
# expected
IdentityFile ~/.ssh/id_rsa

Host test

Host test2
  HostName google.com
```

rather than:

```
Host test
  IdentityFile ~/.ssh/id_rsa

Host test2
  HostName google.com
```

**Comment by cyjake** [comment]
Oh, about the flag to change the prepend offset, can you change it to something like `beforeFirstSection`? For example, if I were to prepend a new section to following config:

```
IdentityFile ~/.ssh/id_rsa

Host test2
  HostName google.com
```

I can turn on the flag as well to get results like:

```
IdentityFile ~/.ssh/id_rsa

Host newlyAdded
  HostName newly.added

Host test2
  HostName google.com
```

If the flag is on but no section were found, just append the object to the end of the config.

**Comment by cyjake** [comment]
btw, I've updated master branch to see if we can trigger CI on pull request. Please rebase master before pushing branch.

**Comment by tanhakabir** [comment]
@cyjake thanks for your feedback! Made the appropriate changes!

**Pull request merged**
